# Generated by Django 3.2.5 on 2021-07-27 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('curso', models.CharField(max_length=255)),
                ('duracion', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.categoria')),
                ('id_modalidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.modalidad')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'db_table': 'courses',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PeriodoLectivo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('perido', models.CharField(max_length=255)),
                ('fechaInicio', models.DateTimeField()),
                ('fehaCierre', models.DateTimeField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.curso')),
            ],
            options={
                'verbose_name': 'Periodo Lectivo',
                'verbose_name_plural': 'Periodos Lectivos',
                'db_table': 'periodo_lectivo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('frecuencia', models.CharField(max_length=50)),
                ('horaInicio', models.CharField(max_length=12)),
                ('horaFin', models.CharField(max_length=12)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
                ('cursos', models.ManyToManyField(to='app.Curso')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'db_table': 'horarios',
                'ordering': ['frecuencia'],
            },
        ),
    ]
